import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";

const repoRoot = process.cwd();
const checkPackageScript = join(repoRoot, "scripts", "check-package.mjs");
const deployScript = join(repoRoot, "scripts", "deploy.mjs");
const releaseBundleScript = join(repoRoot, "scripts", "create-release-bundle.mjs");

const tempRoots: string[] = [];

async function makeTempRoot(prefix: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), prefix));
  tempRoots.push(root);
  return root;
}

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

async function runNodeScript(
  scriptPath: string,
  cwd: string,
  env: Record<string, string | undefined> = {},
): Promise<{
  exitCode: number | undefined;
  logs: string;
  errors: string;
}> {
  const previousCwd = process.cwd();
  const previousExitCode = process.exitCode;
  const previousEnv = new Map<string, string | undefined>();
  for (const [key, value] of Object.entries(env)) {
    previousEnv.set(key, process.env[key]);
    if (value === undefined) {
      delete process.env[key];
      continue;
    }
    process.env[key] = value;
  }
  const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
  const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
  process.chdir(cwd);
  process.exitCode = undefined;

  try {
    const scriptUrl = `${pathToFileURL(scriptPath).href}?v=${Date.now()}-${Math.random()}`;
    await import(scriptUrl);
    return {
      exitCode: process.exitCode,
      logs: logSpy.mock.calls.map((call) => call.map((value) => String(value)).join(" ")).join("\n"),
      errors: errorSpy.mock.calls.map((call) => call.map((value) => String(value)).join(" ")).join("\n"),
    };
  } finally {
    process.chdir(previousCwd);
    process.exitCode = previousExitCode;
    for (const [key, value] of previousEnv) {
      if (value === undefined) {
        delete process.env[key];
        continue;
      }
      process.env[key] = value;
    }
    logSpy.mockRestore();
    errorSpy.mockRestore();
  }
}

async function writePackageFixture(root: string, includeAvatarModule = true): Promise<void> {
  await mkdir(join(root, "src", "generated"), { recursive: true });
  await mkdir(join(root, "src", "styles"), { recursive: true });
  await mkdir(join(root, "assets"), { recursive: true });

  await writeFile(
    join(root, "package.json"),
    JSON.stringify(
      {
        name: "codex-noteforge",
        version: "0.1.0",
        scripts: {
          build: "noop",
          "build:avatar": "noop",
          "build:bundle": "noop",
          "build:smoke": "noop",
          "build:styles": "noop",
          check: "noop",
          "check:package": "noop",
          deploy: "noop",
          lint: "noop",
          "release:bundle": "noop",
          test: "noop",
          "test:smoke": "noop",
          typecheck: "noop",
        },
      },
      null,
      2,
    ),
    "utf8",
  );

  await writeFile(
    join(root, "manifest.json"),
    JSON.stringify(
      {
        id: "obsidian-codex-study",
        version: "0.1.0",
      },
      null,
      2,
    ),
    "utf8",
  );
  await writeFile(
    join(root, "versions.json"),
    JSON.stringify(
      {
        "0.1.0": "1.5.0",
      },
      null,
      2,
    ),
    "utf8",
  );
  await writeFile(join(root, "main.js"), "bundle\n", "utf8");
  await writeFile(join(root, "styles.css"), "body {}\n", "utf8");
  await writeFile(join(root, "assets", "Gemini_Generated_Image_n5otwzn5otwzn5ot.png"), "avatar-source\n", "utf8");

  if (includeAvatarModule) {
    await writeFile(
      join(root, "src", "generated", "chatAvatar.ts"),
      [
        "// Generated by scripts/build-avatar.py",
        "export const CHAT_AVATAR_DATA_URL = 'data:image/png;base64,ZmFrZQ==' as const;",
        "",
      ].join("\n"),
      "utf8",
    );
  }
}

describe("release scripts", () => {
  it("verifies the package and avatar assets without regenerating them during build", async () => {
    const root = await makeTempRoot("obsidian-codex-release-check-");
    await writePackageFixture(root);

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain("Package check passed.");
    expect(result.errors).toBe("");
  });

  it("fails the package check when the generated avatar module is missing", async () => {
    const root = await makeTempRoot("obsidian-codex-release-check-missing-");
    await writePackageFixture(root, false);

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("src/generated/chatAvatar.ts");
  });

  it("requires an explicit deploy target", async () => {
    const root = await makeTempRoot("obsidian-codex-release-deploy-missing-");
    await writePackageFixture(root);

    const result = await runNodeScript(deployScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("CODEX_NOTEFORGE_PLUGIN_DIR");
  });

  it("copies the bundle into the explicit deploy target", async () => {
    const sourceRoot = await makeTempRoot("obsidian-codex-release-deploy-");
    const targetRoot = await makeTempRoot("obsidian-codex-release-target-");
    await writePackageFixture(sourceRoot);
    await writeFile(join(sourceRoot, "assets", "note.txt"), "asset payload\n", "utf8");

    const result = await runNodeScript(deployScript, sourceRoot, {
      CODEX_NOTEFORGE_PLUGIN_DIR: targetRoot,
    });

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain(targetRoot);
    expect(await readFile(join(targetRoot, "main.js"), "utf8")).toBe("bundle\n");
    expect(await readFile(join(targetRoot, "manifest.json"), "utf8")).toContain('"id": "obsidian-codex-study"');
    expect(await readFile(join(targetRoot, "styles.css"), "utf8")).toBe("body {}\n");
    expect(await readFile(join(targetRoot, "assets", "note.txt"), "utf8")).toBe("asset payload\n");
  });

  it("creates a versioned release zip for the plugin bundle", async () => {
    const root = await makeTempRoot("obsidian-codex-release-bundle-");
    await writePackageFixture(root);
    await writeFile(join(root, "assets", "note.txt"), "asset payload\n", "utf8");

    const result = await runNodeScript(releaseBundleScript, root);
    const releaseZipPath = join(root, "release", "obsidian-codex-study-v0.1.0.zip");
    const zipBuffer = await readFile(releaseZipPath);

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain(releaseZipPath);
    expect(zipBuffer.subarray(0, 2).toString("utf8")).toBe("PK");
    expect(zipBuffer.byteLength).toBeGreaterThan(100);
  });
});
