import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";

const repoRoot = process.cwd();
const buildAvatarScript = join(repoRoot, "scripts", "build-avatar.mjs");
const buildStylesScript = join(repoRoot, "scripts", "build-styles.mjs");
const checkPackageScript = join(repoRoot, "scripts", "check-package.mjs");
const deployScript = join(repoRoot, "scripts", "deploy.mjs");
const loadBuiltPluginSmokeScript = join(repoRoot, "scripts", "load-built-plugin-smoke.mjs");
const releaseBundleScript = join(repoRoot, "scripts", "create-release-bundle.mjs");
const spawnHelperScript = join(repoRoot, "scripts", "lib", "spawn.mjs");

const tempRoots: string[] = [];

async function makeTempRoot(prefix: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), prefix));
  tempRoots.push(root);
  return root;
}

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

async function runNodeScript(
  scriptPath: string,
  cwd: string,
  env: Record<string, string | undefined> = {},
  projectRoot = cwd,
): Promise<{
  exitCode: number | undefined;
  logs: string;
  errors: string;
}> {
  const previousCwd = process.cwd();
  const previousExitCode = process.exitCode;
  const previousEnv = new Map<string, string | undefined>();
  const mergedEnv: Record<string, string | undefined> = {
    CODEX_NOTEFORGE_PROJECT_ROOT: projectRoot,
    ...env,
  };
  for (const [key, value] of Object.entries(mergedEnv)) {
    previousEnv.set(key, process.env[key]);
    if (value === undefined) {
      delete process.env[key];
      continue;
    }
    process.env[key] = value;
  }
  const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
  const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
  process.chdir(cwd);
  process.exitCode = undefined;

  try {
    const scriptUrl = `${pathToFileURL(scriptPath).href}?v=${Date.now()}-${Math.random()}`;
    await import(scriptUrl);
    return {
      exitCode: process.exitCode,
      logs: logSpy.mock.calls.map((call) => call.map((value) => String(value)).join(" ")).join("\n"),
      errors: errorSpy.mock.calls.map((call) => call.map((value) => String(value)).join(" ")).join("\n"),
    };
  } finally {
    process.chdir(previousCwd);
    process.exitCode = previousExitCode;
    for (const [key, value] of previousEnv) {
      if (value === undefined) {
        delete process.env[key];
        continue;
      }
      process.env[key] = value;
    }
    logSpy.mockRestore();
    errorSpy.mockRestore();
  }
}

async function writePackageFixture(root: string, includeAvatarModule = true): Promise<void> {
  await mkdir(join(root, "src", "generated"), { recursive: true });
  await mkdir(join(root, "src", "styles"), { recursive: true });
  await mkdir(join(root, "assets"), { recursive: true });

  await writeFile(
    join(root, "package.json"),
    JSON.stringify(
      {
        name: "codex-noteforge",
        version: "0.1.0",
        scripts: {
          build: "noop",
          "build:avatar": "noop",
          "build:bundle": "noop",
          "build:smoke": "noop",
          "build:styles": "noop",
          check: "noop",
          "check:package": "noop",
          deploy: "noop",
          lint: "noop",
          "release:bundle": "noop",
          test: "noop",
          "test:smoke": "noop",
          typecheck: "noop",
        },
      },
      null,
      2,
    ),
    "utf8",
  );

  await writeFile(
    join(root, "manifest.json"),
    JSON.stringify(
      {
        id: "obsidian-codex-study",
        name: "Codex Noteforge",
        version: "0.1.0",
      },
      null,
      2,
    ),
    "utf8",
  );
  await writeFile(
    join(root, "versions.json"),
    JSON.stringify(
      {
        "0.1.0": "1.5.0",
      },
      null,
      2,
    ),
    "utf8",
  );
  await writeFile(join(root, "main.js"), "bundle\n", "utf8");
  await writeFile(join(root, "styles.css"), "body {}\n", "utf8");
  await writeFile(join(root, "assets", "chat-avatar-source.png"), "avatar-source\n", "utf8");

  if (includeAvatarModule) {
    const avatarSourceHash = createHash("sha256").update("avatar-source\n").digest("hex");
    await writeFile(
      join(root, "src", "generated", "chatAvatar.ts"),
      [
        "// Generated by scripts/build-avatar.py",
        `// Source image SHA-256: ${avatarSourceHash}`,
        "export const CHAT_AVATAR_DATA_URL = 'data:image/png;base64,ZmFrZQ==' as const;",
        "",
      ].join("\n"),
      "utf8",
    );
  }
}

async function makeNestedWorkingDir(root: string): Promise<string> {
  const cwd = join(root, "tmp", "nested");
  await mkdir(cwd, { recursive: true });
  return cwd;
}

function listZipEntries(buffer: Buffer): string[] {
  const eocdSignature = 0x06054b50;
  const centralDirectorySignature = 0x02014b50;
  let eocdOffset = -1;
  for (let index = buffer.length - 22; index >= 0; index -= 1) {
    if (buffer.readUInt32LE(index) === eocdSignature) {
      eocdOffset = index;
      break;
    }
  }
  if (eocdOffset < 0) {
    throw new Error("Missing EOCD record.");
  }
  const centralDirectorySize = buffer.readUInt32LE(eocdOffset + 12);
  const centralDirectoryOffset = buffer.readUInt32LE(eocdOffset + 16);
  const entries: string[] = [];
  let cursor = centralDirectoryOffset;
  const end = centralDirectoryOffset + centralDirectorySize;
  while (cursor < end) {
    if (buffer.readUInt32LE(cursor) !== centralDirectorySignature) {
      throw new Error("Malformed central directory.");
    }
    const fileNameLength = buffer.readUInt16LE(cursor + 28);
    const extraLength = buffer.readUInt16LE(cursor + 30);
    const commentLength = buffer.readUInt16LE(cursor + 32);
    entries.push(buffer.toString("utf8", cursor + 46, cursor + 46 + fileNameLength));
    cursor += 46 + fileNameLength + extraLength + commentLength;
  }
  return entries;
}

describe("release scripts", () => {
  it("verifies the package and avatar assets without regenerating them during build", async () => {
    const root = await makeTempRoot("obsidian-codex-release-check-");
    await writePackageFixture(root);
    const cwd = await makeNestedWorkingDir(root);

    const result = await runNodeScript(checkPackageScript, cwd, {}, root);

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain("Package check passed.");
    expect(result.errors).toBe("");
  });

  it("fails the package check when the generated avatar module is missing", async () => {
    const root = await makeTempRoot("obsidian-codex-release-check-missing-");
    await writePackageFixture(root, false);

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("src/generated/chatAvatar.ts");
  });

  it("fails the package check when the stable avatar source is missing", async () => {
    const root = await makeTempRoot("obsidian-codex-release-avatar-missing-");
    await writePackageFixture(root);
    await rm(join(root, "assets", "chat-avatar-source.png"));
    await writeFile(join(root, "assets", "Gemini_Generated_Image_n5otwzn5otwzn5ot.png"), "legacy-avatar-source\n", "utf8");

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("assets/chat-avatar-source.png");
  });

  it("fails the package check when the generated avatar module hash is stale", async () => {
    const root = await makeTempRoot("obsidian-codex-release-avatar-stale-");
    await writePackageFixture(root);
    await writeFile(
      join(root, "src", "generated", "chatAvatar.ts"),
      [
        "// Generated by scripts/build-avatar.py",
        `// Source image SHA-256: ${"0".repeat(64)}`,
        "export const CHAT_AVATAR_DATA_URL = 'data:image/png;base64,ZmFrZQ==' as const;",
        "",
      ].join("\n"),
      "utf8",
    );

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("src/generated/chatAvatar.ts is out of sync with assets/chat-avatar-source.png");
  });

  it("fails the package check with a stable message when src/styles is missing", async () => {
    const root = await makeTempRoot("obsidian-codex-release-styles-missing-");
    await writePackageFixture(root);
    await rm(join(root, "src", "styles"), { recursive: true, force: true });

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("src/styles directory is missing.");
  });

  it("fails the package check when the manifest product name drifts", async () => {
    const root = await makeTempRoot("obsidian-codex-release-name-drift-");
    await writePackageFixture(root);
    await writeFile(
      join(root, "manifest.json"),
      JSON.stringify(
        {
          id: "obsidian-codex-study",
          name: "Obsidian Codex Study",
          version: "0.1.0",
        },
        null,
        2,
      ),
      "utf8",
    );

    const result = await runNodeScript(checkPackageScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("expected product name (Codex Noteforge)");
  });

  it("builds styles from source files even when invoked outside the project root", async () => {
    const root = await makeTempRoot("obsidian-codex-release-build-styles-");
    await mkdir(join(root, "src", "styles"), { recursive: true });
    await writeFile(join(root, "src", "styles", "20-buttons.css"), ".buttons { color: blue; }\n", "utf8");
    await writeFile(join(root, "src", "styles", "10-reset.css"), ".reset { margin: 0; }\n", "utf8");
    const cwd = await makeNestedWorkingDir(root);

    const result = await runNodeScript(buildStylesScript, cwd, {}, root);

    expect(result.exitCode).toBeUndefined();
    expect(await readFile(join(root, "styles.css"), "utf8")).toBe(
      [".reset { margin: 0; }", "", ".buttons { color: blue; }", ""].join("\n"),
    );
  });

  it("falls back from python3 to python when the first interpreter is missing Pillow", async () => {
    const root = await makeTempRoot("obsidian-codex-build-avatar-fallback-");
    const binDir = join(root, "bin");
    await mkdir(join(root, "scripts"), { recursive: true });
    await mkdir(join(root, "src", "generated"), { recursive: true });
    await mkdir(binDir, { recursive: true });
    await writeFile(join(root, "scripts", "build-avatar.py"), "# placeholder\n", "utf8");
    await writeFile(
      join(binDir, "python3"),
      [
        "#!/bin/sh",
        "echo \"Pillow is required to build the assistant avatar. Install it in the Python environment used for this command.\" >&2",
        "exit 1",
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o755 },
    );
    await writeFile(
      join(binDir, "python"),
      [
        "#!/bin/sh",
        "output=\"src/generated/chatAvatar.ts\"",
        "prev=\"\"",
        "for arg in \"$@\"; do",
        "  if [ \"$prev\" = \"--output\" ]; then",
        "    output=\"$arg\"",
        "  fi",
        "  prev=\"$arg\"",
        "done",
        "mkdir -p \"$(dirname \"$output\")\"",
        "cat <<'EOF' > \"$output\"",
        "// Generated by scripts/build-avatar.py",
        `// Source image SHA-256: ${"f".repeat(64)}`,
        "export const CHAT_AVATAR_DATA_URL = 'data:image/png;base64,ZmFrZQ==' as const;",
        "",
        "EOF",
        "exit 0",
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o755 },
    );

    const result = await runNodeScript(
      buildAvatarScript,
      root,
      {
        PATH: `${binDir}:${process.env.PATH ?? ""}`,
      },
      root,
    );

    expect(result.exitCode).toBeUndefined();
    expect(await readFile(join(root, "src", "generated", "chatAvatar.ts"), "utf8")).toContain("CHAT_AVATAR_DATA_URL");
  });

  it("requires an explicit deploy target", async () => {
    const root = await makeTempRoot("obsidian-codex-release-deploy-missing-");
    await writePackageFixture(root);

    const result = await runNodeScript(deployScript, root);

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("CODEX_NOTEFORGE_PLUGIN_DIR");
  });

  it("copies the bundle into the explicit deploy target", async () => {
    const sourceRoot = await makeTempRoot("obsidian-codex-release-deploy-");
    const targetRoot = await makeTempRoot("obsidian-codex-release-target-");
    await writePackageFixture(sourceRoot);
    await writeFile(join(sourceRoot, "assets", "note.txt"), "asset payload\n", "utf8");

    const result = await runNodeScript(deployScript, sourceRoot, {
      CODEX_NOTEFORGE_PLUGIN_DIR: targetRoot,
    });

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain(targetRoot);
    expect(await readFile(join(targetRoot, "main.js"), "utf8")).toBe("bundle\n");
    expect(await readFile(join(targetRoot, "manifest.json"), "utf8")).toContain('"id": "obsidian-codex-study"');
    expect(await readFile(join(targetRoot, "styles.css"), "utf8")).toBe("body {}\n");
    await expect(readFile(join(targetRoot, "assets", "note.txt"), "utf8")).rejects.toThrow();
  });

  it("rejects deploy when source files are newer than the built bundle", async () => {
    const sourceRoot = await makeTempRoot("obsidian-codex-release-deploy-stale-");
    const targetRoot = await makeTempRoot("obsidian-codex-release-target-stale-");
    await writePackageFixture(sourceRoot);
    const oldTime = new Date(Date.now() - 60_000);
    await utimes(join(sourceRoot, "main.js"), oldTime, oldTime);
    await mkdir(join(sourceRoot, "src", "app"), { recursive: true });
    await writeFile(join(sourceRoot, "src", "app", "changed.ts"), "export const changed = true;\n", "utf8");

    const result = await runNodeScript(deployScript, sourceRoot, {
      CODEX_NOTEFORGE_PLUGIN_DIR: targetRoot,
    });

    expect(result.exitCode).toBe(1);
    expect(result.errors).toContain("main.js is older than source files");
  });

  it("creates a versioned release zip for the plugin bundle", async () => {
    const root = await makeTempRoot("obsidian-codex-release-bundle-");
    await writePackageFixture(root);
    await writeFile(join(root, "assets", "note.txt"), "asset payload\n", "utf8");

    const result = await runNodeScript(releaseBundleScript, root);
    const releaseZipPath = join(root, "release", "obsidian-codex-study-v0.1.0.zip");
    const zipBuffer = await readFile(releaseZipPath);

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain(releaseZipPath);
    expect(zipBuffer.subarray(0, 2).toString("utf8")).toBe("PK");
    expect(zipBuffer.byteLength).toBeGreaterThan(100);
    expect(zipBuffer.toString("utf8")).not.toContain("assets/note.txt");
    expect(listZipEntries(zipBuffer)).toEqual([
      "obsidian-codex-study/main.js",
      "obsidian-codex-study/manifest.json",
      "obsidian-codex-study/styles.css",
    ]);

    const rerunResult = await runNodeScript(releaseBundleScript, root);
    const rerunZipBuffer = await readFile(releaseZipPath);

    expect(rerunResult.exitCode).toBeUndefined();
    expect(Buffer.compare(zipBuffer, rerunZipBuffer)).toBe(0);
  });

  it("surfaces spawn errors through the shared helper", async () => {
    const moduleUrl = `${pathToFileURL(spawnHelperScript).href}?v=${Date.now()}-${Math.random()}`;
    const helper = await import(moduleUrl);

    await expect(
      helper.runCommand("codex-noteforge-missing-command", [], {
        cwd: repoRoot,
        stdio: "pipe",
        shell: false,
      }),
    ).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("loads the built bundle with an Obsidian stub during smoke verification", async () => {
    const root = await makeTempRoot("obsidian-codex-release-smoke-");
    await writePackageFixture(root);
    await writeFile(
      join(root, "main.js"),
      [
        "const { Plugin } = require('obsidian');",
        "module.exports = class DemoPlugin extends Plugin {};",
        "",
      ].join("\n"),
      "utf8",
    );

    const result = await runNodeScript(loadBuiltPluginSmokeScript, root);

    expect(result.exitCode).toBeUndefined();
    expect(result.logs).toContain("Bundle load smoke passed.");
    expect(result.errors).toBe("");
  });
});
