import { createHash } from "node:crypto";
import { access, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { resolveProjectRoot } from "./lib/project-root.mjs";

const projectRoot = resolveProjectRoot(import.meta.url);
const avatarSourcePath = path.join(projectRoot, "assets", "chat-avatar-source.png");
const avatarGeneratedPath = path.join(projectRoot, "src", "generated", "chatAvatar.ts");
const expectedPackageName = "vaultforgian";
const expectedManifestId = "obsidian-codex-study";
const expectedManifestName = "VaultForgian";

async function assertReadable(filePath) {
  await access(filePath);
  const fileStat = await stat(filePath);
  if (!fileStat.isFile() || fileStat.size === 0) {
    throw new Error(`Expected non-empty file: ${path.relative(projectRoot, filePath)}`);
  }
}

async function assertDirectory(filePath, label) {
  try {
    const fileStat = await stat(filePath);
    if (!fileStat.isDirectory()) {
      throw new Error(`${label} directory is missing.`);
    }
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      throw new Error(`${label} directory is missing.`);
    }
    throw error;
  }
}

function hashAvatarSource(content) {
  return createHash("sha256").update(content).digest("hex");
}

function extractGeneratedAvatarSourceHash(generatedModule) {
  const match = generatedModule.match(/^\/\/ Source image SHA-256: ([a-f0-9]{64})$/m);
  return match?.[1] ?? null;
}

async function main() {
  const packageJsonPath = path.join(projectRoot, "package.json");
  const manifestPath = path.join(projectRoot, "manifest.json");
  const mainJsPath = path.join(projectRoot, "main.js");
  const stylesPath = path.join(projectRoot, "styles.css");
  const versionsPath = path.join(projectRoot, "versions.json");

  await Promise.all([
    assertReadable(packageJsonPath),
    assertReadable(manifestPath),
    assertReadable(mainJsPath),
    assertReadable(stylesPath),
    assertReadable(versionsPath),
    assertReadable(avatarSourcePath),
    assertReadable(avatarGeneratedPath),
  ]);

  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const versions = JSON.parse(await readFile(versionsPath, "utf8"));
  const [avatarSource, avatarGenerated] = await Promise.all([
    readFile(avatarSourcePath),
    readFile(avatarGeneratedPath, "utf8"),
  ]);

  if (!packageJson?.name || typeof packageJson.name !== "string") {
    throw new Error("package.json is missing a valid name.");
  }
  if (!manifest?.id || typeof manifest.id !== "string") {
    throw new Error("manifest.json is missing a valid id.");
  }
  if (packageJson.name !== expectedPackageName) {
    throw new Error(`package.json name (${packageJson.name}) does not match expected public package name (${expectedPackageName}).`);
  }
  if (manifest.id !== expectedManifestId) {
    throw new Error(`manifest.json id (${manifest.id}) does not match expected stable plugin id (${expectedManifestId}).`);
  }
  if (manifest.name !== expectedManifestName) {
    throw new Error(`manifest.json name (${manifest.name}) does not match expected product name (${expectedManifestName}).`);
  }
  if (packageJson.version !== manifest.version) {
    throw new Error(`package.json version (${packageJson.version}) does not match manifest version (${manifest.version}).`);
  }
  if (!versions || typeof versions !== "object" || typeof versions[manifest.version] !== "string") {
    throw new Error(`versions.json is missing the current manifest version (${manifest.version}).`);
  }
  if (!avatarGenerated.includes("// Generated by scripts/build-avatar.py")) {
    throw new Error("src/generated/chatAvatar.ts is missing the generated-file marker.");
  }
  const avatarSourceHash = hashAvatarSource(avatarSource);
  const generatedSourceHash = extractGeneratedAvatarSourceHash(avatarGenerated);
  if (!generatedSourceHash) {
    throw new Error("src/generated/chatAvatar.ts is missing the source image hash marker.");
  }
  if (generatedSourceHash !== avatarSourceHash) {
    throw new Error("src/generated/chatAvatar.ts is out of sync with assets/chat-avatar-source.png. Run npm run build:avatar.");
  }
  if (!avatarGenerated.includes("CHAT_AVATAR_DATA_URL")) {
    throw new Error("src/generated/chatAvatar.ts is missing the avatar data URL export.");
  }

  const requiredScripts = [
    "build",
    "build:avatar",
    "build:bundle",
    "build:styles",
    "build:smoke",
    "check",
    "check:package",
    "deploy",
    "lint",
    "release:bundle",
    "test",
    "test:smoke",
    "typecheck",
  ];
  const missingScripts = requiredScripts.filter((scriptName) => !packageJson.scripts?.[scriptName]);
  if (missingScripts.length > 0) {
    throw new Error(`package.json is missing required scripts: ${missingScripts.join(", ")}`);
  }

  const stylesSourceDir = path.join(projectRoot, "src/styles");
  await assertDirectory(stylesSourceDir, "src/styles");

  console.log("Package check passed.");
}

await main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
