import { access, readFile, stat } from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const avatarSourcePath = path.join(projectRoot, "assets", "Gemini_Generated_Image_n5otwzn5otwzn5ot.png");
const avatarGeneratedPath = path.join(projectRoot, "src", "generated", "chatAvatar.ts");
const expectedPackageName = "codex-noteforge";
const expectedManifestId = "obsidian-codex-study";

async function assertReadable(filePath) {
  await access(filePath);
  const fileStat = await stat(filePath);
  if (!fileStat.isFile() || fileStat.size === 0) {
    throw new Error(`Expected non-empty file: ${path.relative(projectRoot, filePath)}`);
  }
}

async function main() {
  const packageJsonPath = path.join(projectRoot, "package.json");
  const manifestPath = path.join(projectRoot, "manifest.json");
  const mainJsPath = path.join(projectRoot, "main.js");
  const stylesPath = path.join(projectRoot, "styles.css");

  await Promise.all([
    assertReadable(packageJsonPath),
    assertReadable(manifestPath),
    assertReadable(mainJsPath),
    assertReadable(stylesPath),
    assertReadable(avatarSourcePath),
    assertReadable(avatarGeneratedPath),
  ]);

  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const avatarGenerated = await readFile(avatarGeneratedPath, "utf8");

  if (!packageJson?.name || typeof packageJson.name !== "string") {
    throw new Error("package.json is missing a valid name.");
  }
  if (!manifest?.id || typeof manifest.id !== "string") {
    throw new Error("manifest.json is missing a valid id.");
  }
  if (packageJson.name !== expectedPackageName) {
    throw new Error(`package.json name (${packageJson.name}) does not match expected public package name (${expectedPackageName}).`);
  }
  if (manifest.id !== expectedManifestId) {
    throw new Error(`manifest.json id (${manifest.id}) does not match expected stable plugin id (${expectedManifestId}).`);
  }
  if (packageJson.version !== manifest.version) {
    throw new Error(`package.json version (${packageJson.version}) does not match manifest version (${manifest.version}).`);
  }
  if (!avatarGenerated.includes("// Generated by scripts/build-avatar.py")) {
    throw new Error("src/generated/chatAvatar.ts is missing the generated-file marker.");
  }
  if (!avatarGenerated.includes("CHAT_AVATAR_DATA_URL")) {
    throw new Error("src/generated/chatAvatar.ts is missing the avatar data URL export.");
  }

  const requiredScripts = [
    "build",
    "build:avatar",
    "build:bundle",
    "build:styles",
    "build:smoke",
    "check",
    "check:package",
    "deploy",
    "lint",
    "test",
    "test:smoke",
    "typecheck",
  ];
  const missingScripts = requiredScripts.filter((scriptName) => !packageJson.scripts?.[scriptName]);
  if (missingScripts.length > 0) {
    throw new Error(`package.json is missing required scripts: ${missingScripts.join(", ")}`);
  }

  const stylesSourceDir = path.join(projectRoot, "src/styles");
  const stylesSourceStat = await stat(stylesSourceDir);
  if (!stylesSourceStat.isDirectory()) {
    throw new Error("src/styles directory is missing.");
  }

  console.log("Package check passed.");
}

await main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
